@startuml
package "App (Rutas y Renderización)" {
  component "(home)" {
    [aniadir.tsx]
    [archivados.tsx]
    [citas.tsx]
    [index.tsx]
    [_layout.tsx]
    component "paciente" {
      [agregarCita.tsx]
      [grabaciones.tsx]
      [grabarAudio.tsx]
      [id.tsx]
      [modificarPaciente.tsx]
      [transcripciones.tsx]
    }
    [profile.tsx]
  }
  [index.tsx]
  [_layout.tsx]
  [recuperarContrasenia.tsx]
}

package "Componentes" {
  package "common" {
    [Boton.tsx]
    [InputDatos.tsx]
    [TextoCustom.tsx]
  }
  package "Formulario" {
    [FormIngresoPacientes.tsx]
    [FormInicioSesion.tsx]
    [FormRecuperarContrasenia.tsx]
    [IngresoCita.tsx]
    [InputField.tsx]
    [InputTexto.tsx]
  }
  package "mostrar" {
    [FichaPaciente.tsx]
    [FilaCita.tsx]
    [FilaPaciente.tsx]
    [ListaCitas.tsx]
    [ListaPacientes.tsx]
    [PerfilUsuario.tsx]
  }
}

package "Contextos" {
  [AuthContext.tsx]
  [PacienteContext.tsx]
}

package "Assets" {
  package "audio" {
    [NIGERUNDAYO-SMOKEY.mp3]
    [rahhh.mp3]
  }
  package "fonts" {
    [SpaceMono-Regular.ttf]
  }
  package "images" {
    [adaptive-icon.png]
    [favicon.png]
    [icon.png]
    [partial-react-logo.png]
    [react-logo@2x.png]
    [react-logo@3x.png]
    [react-logo.png]
    [splash.png]
  }
}

[constants/Colors.ts] --> "App (Rutas y Renderización)"
[AuthContext.tsx] --> [App]
[PacienteContext.tsx] --> [App]

[Scripts] --> [App]
@enduml
